# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "74457063ef549ca3a9a8f644b2ae1407"
application_url = "https://jason-thats-actually-erik.trycloudflare.com"
embedded = true
name = "QuickPin Checkout\r\r"
handle = "quickpin-checkout"

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_order_edits,read_orders,read_products,write_order_edits,write_orders,write_products"

[auth]
redirect_urls = [
  "https://jason-thats-actually-erik.trycloudflare.com/auth/callback",
  "https://jason-thats-actually-erik.trycloudflare.com/auth/shopify/callback",
  "https://jason-thats-actually-erik.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false

[app_proxy]
url = "https://jason-thats-actually-erik.trycloudflare.com"
subpath = "quickpin-checkout"
prefix = "apps"
